
[env]
TERM = "xterm-256color"

[general]
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]
working_directory = "~/Documents/Coding"

[window]
dynamic_padding = true
opacity = 0.9
padding = { x = 12, y = 12 }

[font]
normal = { family = "MesloLGM Nerd Font", style = "Regular" } 
bold = { family = "MesloLGM Nerd Font", style = "Bold" } 
italic = { family = "MesloLGM Nerd Font", style = "Italic" } 
bold_italic = { family = "MesloLGM Nerd Font", style = "Bold Italic" } 
